name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test Solution
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: 5.x
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

  publish-to-nuget:
    name: Publish to Nuget.org
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Update Package Version
      uses: cschleiden/replace-tokens@v1
      with:
        files: '["**/*.nuspec"]'
      env:
        VERSION: ${{ needs.build.outputs.semVer }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Pack DynamoDB.Geo.Contract
      run: dotnet pack ~/src/DynamoDB.Geo.Contract/DynamoDB.Geo.Contract.csproj --configuration Release -p:PackageVersion=${{ needs.build.outputs.semVer }} -p:NuspecFile=~/dynamodb-geo-contract.nuspec

    - name: Publish DynamoDB
      run: dotnet nuget push bin/Release/DynamoDB.GeoSpatial.Contract.${{ needs.build.outputs.semVer }}.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json